### ISSUE TITLE
Fix Update and Delete for Meetings and meeting-rooms

### ISSUE THREAD

**Issue by Fredohm** [Fredohm/springbootintranet#93]

**Comment by TortueDeBois** [comment]
Dans l'optique de regarder à l'update d'une meeting room, j'ai inspecté la fonction save de la classe [MeetingRoomSDJpaServiceImpl](https://github.com/Fredohm/springbootintranet/blob/master/springbootintranet-data/src/main/java/org/fredohm/springbootintranet/services/sdjpa/impl/MeetingRoomSDJpaServiceImpl.java)

Received :
MeetingRoomDTO{BaseDTO(id=10, version=null, createdDate=null, lastModifiedDate=null)'name='Salle Mauve', capacity=8, location='SaiPaKoi', description='', available=true, meetings=null}
I will record :
MeetingRoom{BaseEntity(id=10, version=null, createdDate=null, lastModifiedDate=null)'name='Salle Mauve', capacity=8, location='SaiPaKoi', description='', available=true, meetings=null}

La classe reçoit l'id de l'objet à modifier et le mapper crée bien l'entity correspondant.
Mais il semble que Hibernate réalise une query sans id => il crée un nouvel objet à chaque update

Hibernate: insert into meeting_rooms (created_date, last_modified_date, version, available, capacity, description, location, name) values (?, ?, ?, ?, ?, ?, ?, ?)

Je ne sais pas quelle annotation empêche l'utilisation de la bonne query.

**Comment by TortueDeBois** [comment]
Je n'ai toujours pas trouvé ce qui manque.

Je suggère de  créer manuellement la query de l'update (on pourra essayer de la générer automatiquement plus tard si on a le temps).

ça se traduirait par l'ajout dans la classe [MeetingRoomRepository](https://github.com/Fredohm/springbootintranet/blob/master/springbootintranet-data/src/main/java/org/fredohm/springbootintranet/repositories/MeetingRoomRepository.java) de la fonction update avec l'annotion @Query. Ensuite, il faudra l'appeler dans la classe MeetingRoomService.
exemple que j'avais dans mon projet de ce genre de query custom:
@Query("SELECT s FROM PillarEntity s WHERE name = ?1")
    Optional<PillarEntity> findByName(String name);

@Fredohm, qu'en penses tu?
